// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.busko.routemanager.model.transit.gtfs;

import org.busko.routemanager.model.transit.gtfs.Calendar;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Calendar_Roo_Configurable {
    
    declare @type: Calendar: @Configurable;
    
}
