// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.busko.routemanager.model.transit;

import org.busko.routemanager.model.transit.Region;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Region_Roo_Configurable {
    
    declare @type: Region: @Configurable;
    
}
